spring:
   cloud:
      gateway:
         routes:
                        
            - id: provider-service
              uri: lb://PROVIDER-SERVICE
              predicates:
                 - Path=/admin/provider/**
              filters: 
                 - AuthenticationFilter
                 - RoleAuthFilter=ADMIN
                 
            - id: provider-service
              uri: lb://PROVIDER-SERVICE
              predicates:
                 - Path=/user/provider/**
              filters: 
                 - AuthenticationFilter 
                 - RoleAuthFilter=USER                                                              
                                             
            - id: authentication
              uri: lb://AUTHENTICATION
              predicates:
                 - Path=/auth/**
              filters: 
                 - AuthenticationFilter                 
                 
         default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
         
         globalcors:
            corsConfigurations:
             '[/**]':
                 allowedOrigins: "*"
                 allowedMethods: "*"
                 allowedHeaders: "*"     
